# ------------------ Provider / Model ------------------
provider: google
model: imagen-4.0-ultra-generate-001   # Imagen 4 Ultra Generate

# ------------------ Google / Vertex AI ------------------
google:
  project_id: "masters-473910"
  location: "global"             # or a region like 'us-central1' if required
  # Generation settings (Python args use snake_case)
  image_size: "1K"        # "1K" or "2K" → output resolution (1K ≈ 1024 on 1:1)
  aspect_ratio: "1:1"            # "1:1","3:4","4:3","16:9","9:16"
  add_watermark: false           # required for seed determinism
  enhance_prompt: false          # required for seed determinism (seed ignored if true)
  output_mime_type: "image/png"
  include_rai_reason: true
  include_safety_attributes: false
  safety_filter_level: "block_medium_and_above"
  # Optional policy: block people when the prompt says no-people
  person_generation_default: "allow_all"   # allow_all | allow_adult | dont_allow

# ------------------ Output ------------------
output_root: "E:\\research\\google"

# ------------------ Replications -> percent-based seeds ------------------
# We KEEP the 5 labels for filenames (seed-11.png, etc.)
# but convert them to REAL seeds as: floor(p% * (2147483647 - 1)).
seeds: [11, 23, 37, 53, 71]

# ------------------ Reliability / retries ------------------
retry:
  max_attempts: 5
  initial_delay_s: 2
  max_delay_s: 30

timeout_s: 300
concurrency: 4
